AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'bin/bundle'
    - !ruby/regexp /old_and_unused\.rb$/
Documentation:
   Enabled: false
