default: &default
  adapter: mysql2
  encoding: utf8
  username: ENV["DB_USERNAME"]
  password: ENV["DB_PASSWORD"]
  database: arduino
  encoding: utf8

development: 
  <<: *default
  host: terraform-20220201115746165600000001.c50vmmxqsblc.eu-west-2.rds.amazonaws.com

sqliteql2test:
  <<: *default
  host: terraform-20220201115746165600000001.c50vmmxqsblc.eu-west-2.rds.amazonaws.com

production:
  <<: *default
  host: terraform-20220201115746165600000001.c50vmmxqsblc.eu-west-2.rds.amazonaws.com
