default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DCC_USERNAME'] %>
  password: <%= ENV['DCC_PASSWORD'] %> 
  database: arduino
  host:  <%= ENV['DCC_HOST'] %> 
  port:  <%= ENV['DCC_PORT'] %> 

development: 
  <<: *default

sqliteql2test:
  <<: *default

production:
  <<: *default
