default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %> 
  database: arduino
  host: terraform-20220201214334113200000001.c50vmmxqsblc.eu-west-2.rds.amazonaws.com
  port: 3306

development: 
  <<: *default

sqliteql2test:
  <<: *default

production:
  <<: *default
