title: Digital Controller
email: your-email@example.com
logo: /assets/images/dcc.png
github_username:  sfawcett123
heading_anchors: true

# Build settings
remote_theme: pmarsceill/just-the-docs
